# Generated by Django 6.0.4 on 2026-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('estado', models.CharField(default='A', max_length=1)),
                ('usuarioCreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=50, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion', null=True)),
                ('usuarioModificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=50, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_column='fechaModificacion', null=True)),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimoIngreso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
