# Generated by Django 6.0.4 on 2026-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('idAnalysisReport', models.AutoField(db_column='idAnalysisReport', primary_key=True, serialize=False)),
                ('idEmpresa', models.IntegerField(blank=True, db_column='idEmpresa', null=True)),
                ('totalFrames', models.IntegerField(db_column='totalFrames', default=0)),
                ('totalDuracionSegundos', models.FloatField(db_column='totalDuracionSegundos', default=0)),
                ('totalEventos', models.IntegerField(db_column='totalEventos', default=0)),
                ('totalPeleas', models.IntegerField(db_column='totalPeleas', default=0)),
                ('totalDisturbios', models.IntegerField(db_column='totalDisturbios', default=0)),
                ('confianzaPromedio', models.FloatField(db_column='confianzaPromedio', default=0)),
                ('confianzaMaxima', models.FloatField(db_column='confianzaMaxima', default=0)),
                ('tiempoProcesamientoSegundos', models.FloatField(blank=True, db_column='tiempoProcesamientoSegundos', null=True)),
                ('estadisticas', models.JSONField(blank=True, db_column='estadisticas', null=True)),
                ('resumenJson', models.JSONField(blank=True, db_column='resumenJson', null=True)),
                ('rutaJsonKeypoints', models.CharField(blank=True, db_column='rutaJsonKeypoints', max_length=500, null=True)),
                ('generadoEn', models.DateTimeField(auto_now_add=True, db_column='generadoEn')),
                ('actualizadoEn', models.DateTimeField(auto_now=True, db_column='actualizadoEn')),
                ('usuarioCreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=100, null=True)),
                ('usuarioModificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=100, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('fechaModificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
            ],
            options={
                'db_table': 'analysisReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('idDetectionEvent', models.AutoField(db_column='idDetectionEvent', primary_key=True, serialize=False)),
                ('tipoEvento', models.CharField(choices=[('PELEA', 'Pelea'), ('DISTURBIO', 'Disturbio'), ('NORMAL', 'Normal')], db_column='tipoEvento', max_length=20)),
                ('confianza', models.FloatField(db_column='confianza')),
                ('frameInicio', models.IntegerField(db_column='frameInicio')),
                ('frameFin', models.IntegerField(db_column='frameFin')),
                ('tiempoInicio', models.FloatField(db_column='tiempoInicio')),
                ('tiempoFin', models.FloatField(db_column='tiempoFin')),
                ('personasInvolucradas', models.IntegerField(db_column='personasInvolucradas', default=1)),
                ('detalles', models.JSONField(blank=True, db_column='detalles', null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('usuarioCreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=100, null=True)),
                ('usuarioModificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=100, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
            ],
            options={
                'db_table': 'analysisDetectionEvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('idImageUpload', models.AutoField(db_column='idImageUpload', primary_key=True, serialize=False)),
                ('idEmpresa', models.IntegerField(blank=True, db_column='idEmpresa', null=True)),
                ('nombreOriginal', models.CharField(db_column='nombreOriginal', max_length=255)),
                ('rutaArchivoOriginal', models.CharField(db_column='rutaArchivoOriginal', max_length=500)),
                ('rutaArchivoProcesado', models.CharField(blank=True, db_column='rutaArchivoProcesado', max_length=500, null=True)),
                ('tamanioBytes', models.BigIntegerField(db_column='tamanioBytes')),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], db_column='estado', default='PENDING', max_length=20)),
                ('fechaCarga', models.DateTimeField(auto_now_add=True, db_column='fechaCarga')),
                ('fechaProcesamiento', models.DateTimeField(blank=True, db_column='fechaProcesamiento', null=True)),
            ],
            options={
                'db_table': 'analysisImageUpload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonKeypoints',
            fields=[
                ('idPersonKeypoints', models.AutoField(db_column='idPersonKeypoints', primary_key=True, serialize=False)),
                ('personId', models.IntegerField(db_column='personId')),
                ('frameNumber', models.IntegerField(db_column='frameNumber')),
                ('keypointsJson', models.JSONField(db_column='keypointsJson', default=dict)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('usuarioCreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=100, null=True)),
                ('usuarioModificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=100, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
            ],
            options={
                'db_table': 'analysisPersonKeypoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('idParameter', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('INT', 'Entero'), ('FLOAT', 'Decimal'), ('STRING', 'Texto'), ('BOOL', 'Booleano')], default='STRING', max_length=20)),
            ],
            options={
                'db_table': 'systemParameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('idVideoUpload', models.AutoField(db_column='idVideoUpload', primary_key=True, serialize=False)),
                ('idEmpresa', models.IntegerField(blank=True, db_column='idEmpresa', null=True)),
                ('nombreOriginal', models.CharField(db_column='nombreOriginal', max_length=255)),
                ('rutaArchivo', models.CharField(db_column='rutaArchivo', max_length=500)),
                ('tamanioBytes', models.BigIntegerField(db_column='tamanioBytes')),
                ('duracionSegundos', models.FloatField(blank=True, db_column='duracionSegundos', null=True)),
                ('fps', models.FloatField(blank=True, db_column='fps', null=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], db_column='estado', default='PENDING', max_length=20)),
                ('celeryTaskId', models.CharField(blank=True, db_column='celeryTaskId', max_length=255, null=True)),
                ('fechaCarga', models.DateTimeField(auto_now_add=True, db_column='fechaCarga')),
                ('fechaProcesamiento', models.DateTimeField(blank=True, db_column='fechaProcesamiento', null=True)),
            ],
            options={
                'db_table': 'analysisVideoUpload',
                'managed': False,
            },
        ),
    ]
